### ISSUE TITLE
Module version mismatch

### ISSUE THREAD

**Issue by superlou** [RSATom/wcjs-ugly-demo#11]
When trying to run this demo with Electron, I receive the following error on the console:

```
bindings.js:83 Uncaught Error: Module version mismatch. Expected 49, got 48.
```

My node version is 4.4.7 and electron version is 1.3.5.

**Comment by RSATom** [comment]
This means you use .node file built for another Electron version. You should use WebChimera.js built exactly for your Electron version.

**Comment by superlou** [comment]
I'm going to try and build from source for Electron 1.3.5.  I'm going to close for now, as I should learn to read readmes, sorry.

**Comment by RSATom** [comment]
No need build it yourself, I've forced rebuild on CI. Required version will be available soon on Releases
