### ISSUE TITLE
try"wcjs-ugly-demo" step by step errors

### ISSUE THREAD

**Issue by wwwmir3cq** [RSATom/wcjs-ugly-demo#13]
@RSATom:
    When i try "wcjs-ugly-demo" with  WebChimera.js prebuilt on Windows，and by the following instructions:

1. -            run git clone https://github.com/RSATom/wcjs-ugly-demo.git
2. -            run npm install --ignore-scripts
3. -            download WebChimera.js_v0.2.7_nw_v0.18.0_VLC_v2.2.4_x64_win.zip and extract to                                             
                 D:\pdyf\app\nwvlc\app6\wcjs-ugly-demo\node_modules
4. -            run run_nwjs.cmd

   I have got the error:
        D:\pdyf\app\nwvlc\app6\wcjs-ugly-demo\node_modules\webchimera.js\node_modules\bindings\bindings.js:91 Uncaught Error: Could not locate the bindings file. Tried:
 → D:\pdyf\app\nwvlc\app6\wcjs-ugly-demo\node_modules\webchimera.js\build\WebChimera.js.node
 → D:\pdyf\app\nwvlc\app6\wcjs-ugly-demo\node_modules\webchimera.js\build\Debug\WebChimera.js.node
 → D:\pdyf\app\nwvlc\app6\wcjs-ugly-demo\node_modules\webchimera.js\build\Release\WebChimera.js.node
 → D:\pdyf\app\nwvlc\app6\wcjs-ugly-demo\node_modules\webchimera.js\out\Debug\WebChimera.js.node
 → D:\pdyf\app\nwvlc\app6\wcjs-ugly-demo\node_modules\webchimera.js\Debug\WebChimera.js.node
 → D:\pdyf\app\nwvlc\app6\wcjs-ugly-demo\node_modules\webchimera.js\out\Release\WebChimera.js.node
 → D:\pdyf\app\nwvlc\app6\wcjs-ugly-demo\node_modules\webchimera.js\Release\WebChimera.js.node
 → D:\pdyf\app\nwvlc\app6\wcjs-ugly-demo\node_modules\webchimera.js\build\default\WebChimera.js.node
 → D:\pdyf\app\nwvlc\app6\wcjs-ugly-demo\node_modules\webchimera.js\compiled\6.2.2\win32\x64\WebChimera.js.node

what's wrong?

**Comment by garfeng** [comment]
Find where the WebChimera.js.node file is.
such as "./node_modules/webchimera.js/bin/WebChimera.js.node"

Edit the index.html, replace
``` javascript
var player = require("webchimera.js").createPlayer();
```
with:
``` javascript
var player = require("./node_modules/webchimera.js/bin/WebChimera.js.node").createPlayer();
```

**Comment by RSATom** [comment]
It looks like I've missed this issue completely... My fault :(
@wwwmir3cq, did you solve it?

@garfeng, thanks.

**Comment by wwwmir3cq** [comment]
I have solved this problem。
@garfeng,：thanks.
@RSATom：thanks
