### ISSUE TITLE
Uncaught Error: The specified module could not be found.

### ISSUE THREAD

**Issue by CHQ930731** [RSATom/wcjs-ugly-demo#15]
My environment is win10(x64)+node(v8.9.0)+npm(v5.5.1)+nw.js(nwjs-sdk-v0.23.7-win-ia32)+WebChimera.js_v0.2.7_nw_v0.23.7_VLC_v2.2.4_ia32_win.

I have tried **wcjs-ugly-demo** for several times，the following error occurred.

Uncaught Error: The specified module could not be found.
\\?\E:\webchimeraAndNwjs\wcjs-ugly-demo\node_modules\webchimera.js\build\WebChimera.js.node
    at Object.Module._extensions..node (module.js:732:18)
    at Module.load (module.js:598:32)
    at tryModuleLoad (module.js:538:12)
    at Function.Module._load (module.js:530:3)
    at Module.require (module.js:629:17)
    at require (internal/module.js:11:18)
    at bindings (E:\webchimeraAndNwjs\wcjs-ugly-demo\node_modules\bindings\bindings.js:76:44)
    at Object.<anonymous> (E:\webchimeraAndNwjs\wcjs-ugly-demo\node_modules\webchimera.js\index.js:1:99)
    at Module._compile (module.js:685:30)
    at Object.Module._extensions..js (module.js:702:10)

**Comment by 8237** [comment]
Do you have E:\webchimeraAndNwjs\wcjs-ugly-demo\node_modules\webchimera.js\build\WebChimera.js.node on HDD?

**Comment by RSATom** [comment]
I see two possible reasons:
1) you really don't have E:\webchimeraAndNwjs\wcjs-ugly-demo\node_modules\webchimera.js\build\WebChimera.js.node
2) you don't have some dependency dll

**Comment by CHQ930731** [comment]
sure




  
  
  


  
    
      
          
            
              
            
            
              1002291414
            
          
            
              
                  邮箱：1002291414@qq.com
              
            
      
    
  


签名由 网易邮箱大师 定制
On 12/20/2017 15:28, Sergey wrote: Do you have E:\webchimeraAndNwjs\wcjs-ugly-demo\node_modules\webchimera.js\build\WebChimera.js.node on HDD?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/RSATom/wcjs-ugly-demo","title":"RSATom/wcjs-ugly-demo","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/RSATom/wcjs-ugly-demo"}},"updates":{"snippets":[{"icon":"PERSON","message":"@8237 in #15: Do you have E:\\webchimeraAndNwjs\\wcjs-ugly-demo\\node_modules\\webchimera.js\\build\\WebChimera.js.node on HDD?"}],"action":{"name":"View Issue","url":"https://github.com/RSATom/wcjs-ugly-demo/issues/15#issuecomment-352986395"}}}

**Comment by CHQ930731** [comment]
well,
1. i have  "WebChimera.js.node" in the file path on my system.
2. i have put files in "WebChimera.js_v0.2.7_nw_v0.23.7_VLC_v2.2.4_ia32_win." in "E:\webchimeraAndNwjs\wcjs-ugly-demo\node_modules\webchimera.js\build\Release"

**Comment by RSATom** [comment]
What NW.js version do you use?

**Comment by RSATom** [comment]
It's possible WebChimera.js just not compatible with latest NW.js versions. I didn't try it long time.

**Comment by CHQ930731** [comment]
thanks a lot. I' ll try later.

**Comment by calabashdad** [comment]
> thanks a lot. I' ll try later.

hi,  has the problem been solved?  I meet the same situation
I check the WebChimera.js.node use dependency, an error detected

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/6006628/51227066-8c832980-198d-11e9-9dc9-3e8e89cd4036.png">

**Comment by RSATom** [comment]
@calabashdad, did you build WebChimera.js yourself or get prebuilt one?

**Comment by calabashdad** [comment]
> @calabashdad, did you build WebChimera.js yourself or get prebuilt one?

hi，awesome project!  I build WebChimera.js myself according your tutorial
some environmental params:
windows 10 32bit; vlc 3.0.6; electron v4.0.1 ; npm 6.5.0

**Comment by RSATom** [comment]
You should check (in dependancy walker) if it miss some else direct dependancy for `webchimera.js.node` except `node.dll` (just collapse all elements except top level WEBCHIMERA.JS.NODE, and look if it has some more modules with yellow icons with question symbol).
If it not - then try add your Electron folder (where node.dll resides) to PATH and check with Dependancy Walker again if it will have some errors.
Other option could be some compatibility issue with latest Electron, so you could build against older Electron version and check if it will work.

**Comment by RSATom** [comment]
@calabashdad, it looks like it's compatibility issue with Electron v4:
https://github.com/cmake-js/cmake-js/issues/153

**Comment by calabashdad** [comment]
> @calabashdad, it looks like it's compatibility issue with Electron v4:
> [cmake-js/cmake-js#153](https://github.com/cmake-js/cmake-js/issues/153)

@RSATom Thanks for your valuable suggestion!  i try it with electron v4 but compile error,  later i'll check the compilation environment and process again, if successful, I will give a reply here, thanks again
