### ISSUE TITLE
error in run_electron.cmd

### ISSUE THREAD

**Issue by contona68** [RSATom/wcjs-ugly-demo#18]
hi
i used wcjs-ugly-demo in my project
i run code in windows10 x64  and used 
`WebChimera.js_electron_1.3.3_ia32_win.zip`
`WebChimera.js_v0.2.6_electron_v1.3.3_VLC_v2.2.4_ia32_win.zip .`
but when i run run_electron.cmd to run player i see this  error

![image](https://user-images.githubusercontent.com/44703339/50375406-f4a25200-0611-11e9-892e-43722981b7af.png)

i dont What this?

**Comment by RSATom** [comment]
You have to build it (WebChimera.js) yourself from sources for your Electron version.

**Comment by contona68** [comment]
> You have to build it (WebChimera.js) yourself from sources for your Electron version.

thanks for your help.it run without error
