### ISSUE TITLE
The demo runs nicely in dev mode but failed to run after electron app packaging.

### ISSUE THREAD

**Issue by hnguyen48206** [RSATom/wcjs-ugly-demo#19]
Hi,

Thank you sir for your great works including this demo project. I have tried it to test the ability to run hevc from electron and everything worked as it should. However, there's an error after building the app to OS runable files, it works ok in Windows but not in Linux (I have used both electrion-builder and electron-packager but still the same result so it's probably not about the build tools). Below is the log message when I first start the app, any suggestion would be much appricated:

My nodejs version is: 10.24.1

```
A JavaScript error occurred in the main process
Uncaught Exception:
/home/abc/Downloads/wcjs-ugly-demo/dist/linux-unpacked/resources/app.asar/index.html:2
<!DOCTYPE html>
^

SyntaxError: Unexpected token '<'
    at wrapSafe (internal/modules/cjs/loader.js:1060:16)
    at Module._compile (internal/modules/cjs/loader.js:1108:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Object.<anonymous> (electron/js2c/browser_init.js:185:3510)
    at Object../lib/browser/init.ts (electron/js2c/browser_init.js:185:3714)
    at _webpack_require_ (electron/js2c/browser_init.js:1:128)
    at electron/js2c/browser_init.js:1:1200
```
And this is my package.json

```
{
  "name": "testelectron",
  "productName": "ivms",
  "description": "basic demo for WebChimera.js",
  "version": "0.2.0",
  "private": true,
  "main": "index.html",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "package-linux": "electron-packager . testelectron --overwrite --asar=true --platform=linux --arch=x64 --icon=assets/icons/linux/icon.png --prune=true --out=release-builds",
    "pack": "electron-builder --dir",
    "dist": "electron-builder"
  },
  "build": {
    "appId": "testelectron",
    "icon": "assets/icons/linux/icon.png",
    "linux": {
      "target": "AppImage"
    }
  },
  "dependencies": {
    "webchimera.js": "*",
    "webgl-video-renderer": ">=0.2.0"
  },
  "cmake-js": {
    "runtime": "nw",
    "runtimeVersion": "0.16.0"
  },
  "env": "development",
  "devDependencies": {
    "electron": "^11.5.0",
    "electron-builder": "^22.10.5",
    "electron-packager": "^15.4.0"
  },
  "postinstall": "electron-builder install-app-deps"
}

```

**Comment by RSATom** [comment]
It's totally broken on Linux: https://github.com/RSATom/WebChimera.js/issues/146#issuecomment-856913163

**Comment by hnguyen48206** [comment]
Thank sir for your quick response. As I have read through the comments in the post you mentioned, is it just the matter with electron itself (built in ffmpeg) and by using other frameworks out there such as nw.js, neutralinojs, etc. we can overcome it and still be able to use libvlc on Linux?

**Comment by RSATom** [comment]
What do you mean by "overcome"? You can use libvlc directly.

**Comment by hnguyen48206** [comment]
This is where I get lost sir, do you mean using libray such as this one instead of webchimera: https://github.com/tjfontaine/node-vlc ? I have taken a look at it and a few similar ones but still have no idea how to get the frames and draw it over html like what chimera has done.

**Comment by RSATom** [comment]
@hnguyen48206 All I want to say, right now there is no way to use libvlc with standard Electron version on linux.

**Comment by hnguyen48206** [comment]
Since there is no way to use Electron with webchimera on Linux, I have switched to NW.js as the alternative but after trying a couple versions of webchimera releases, I keep geeting the error 'the module did not self-register' and it seems like the problem is in the node version shipped with nw.js it self. Do you have any combo version of nwjs and webchimera that actually does work well together?

**Comment by RSATom** [comment]
No, I didn't try to use NW.js long time already.

**Comment by hnguyen48206** [comment]
Thank you sir, your answers still help me save lots of time. To anyone who comes accross this same matter, the versions of nw.js and webchimera.js you need to use are: 0.18.1 and 0.2.7 which are pretty old though.
