### ISSUE TITLE
Capturing a window stream

### ISSUE THREAD

**Issue by anesuc** [RSATom/wcjs-ugly-demo#20]
Hi all,

I know this is kinda not actively maintained, but I found that I had code for this on my computer which makes this perfect for what I am trying to accomplish. I was trying all these tcp solutions but there was always this delay.

Anyway how do I go about capturing a video stream of a window? for example this command works from commandline:
```
gst-launch-1.0 ximagesrc xid=0x03c0002c ! videoconvert ! autovideosink
```

I have tried all kinds of variations trying to keep the app link but I got a blank screen. I think the closest I got was some noise video wise but it seemed like incorrect format but was reading the stream with something like this:
```
ximagesrc xid=0x03c0002c ! queue ! decodebin name=d  d. ! queue ! videoconvert ! appsink name=sink  d.
```

Any ideas?

Thanks

**Comment by RSATom** [comment]
@anesuc this demo uses `webgl-video-renderer` for rendering video frames. And it expects i420 video format. But  `ximagesrc` produces RGB video frames. So you need to find some way how to convert RGB video frames to i420 video frames. Or just modify app to render RGB frames directly.

**Comment by anesuc** [comment]
Awesome thanks for the info! For anyone coming across this thread in the future this fixed it:

```
ximagesrc xid=0x03c0002c ! queue ! decodebin name=d  d. ! queue ! videoconvert ! video/x-raw,format=I420 ! appsink name=sink  d.
```

**Comment by RSATom** [comment]
@anesuc It's highly possible you don't need `decodebin` there and `videoconvert` will be enough.
Something like:
```
ximagesrc xid=0x03c0002c ! queue ! videoconvert ! video/x-raw,format=I420 ! appsink name=sink
```

**Comment by anesuc** [comment]
> @anesuc It's highly possible you don't need `decodebin` there and `videoconvert` will be enough. Something like:
> 
> ```
> ximagesrc xid=0x03c0002c ! queue ! videoconvert ! video/x-raw,format=I420 ! appsink name=sink
> ```

Cool! One last question. Ideas on adjusting alpha of certain colours before passing it into the render function? I noticed the data is like unit8Array but not sure how to interpret the colours from it in terms of rgba and adjusting accordingly? I.e lets say I want to key out certain colours like a green screen kind of thing

**Comment by RSATom** [comment]
https://gstreamer.freedesktop.org/documentation/alpha/index.html ?

**Comment by anesuc** [comment]
> https://gstreamer.freedesktop.org/documentation/alpha/index.htm ?

Alright I may potentially use this. However, I would like to dynamically make a decision to apply alpha on certain colours or not. Like sometimes not apply alpha but sometimes do it but in real time.

Also side note, link was missing an "l" at the end aka html incase someone wants to look at it.

**Comment by RSATom** [comment]
@anesuc with I420 it will be pretty complected to alter frames, so I would recommend you switch to rendering of rgb frames. If I remember correctly https://github.com/Magics-Group/wcjs-renderer had support for rendering of rgb frames, but I'm not sure 100%...

**Comment by RSATom** [comment]
Other possible way - make your own renderer based on `webgl-video-renderer` and modify video frames on WebGL shaders level.

**Comment by anesuc** [comment]
@RSATom  I have noticed that firefox is now doing this. This might just be some weird thing on my local system as I have only noticed it on firefox and I think firefox looked fine before 
![image](https://github.com/RSATom/wcjs-ugly-demo/assets/17863266/493667dd-20be-47c2-bbc5-63aeb336b53a)

**Comment by anesuc** [comment]
Ignore the last message it fixed itself after resizing the window and restarting the app. The size of the window apparently made this happen which is fascinating
